"""KiCad CLI oracle — detect, version, ERC, DRC, and structured results.

Usage:
    from zaptrace.kicad.oracle import detect_kicad, run_erc, run_drc

    oracle = detect_kicad()
    if oracle.available:
        erc_result = run_erc("/path/to/project.kicad_pro")
        drc_result = run_drc("/path/to/board.kicad_pcb")

Every method returns a result object — never raises.  When the CLI is
unavailable the result carries ``available=False`` and an explanatory message.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from contextlib import suppress
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast

# ======================================================================
# Known KiCad install paths per platform
# ======================================================================

_COMMON_KICAD_PATHS: list[str] = [
    # Linux (AppImage, apt, snap)
    "kicad-cli",
    "/usr/bin/kicad-cli",
    "/usr/local/bin/kicad-cli",
    "/snap/bin/kicad-cli",
    # macOS
    "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
    "/Applications/KiCad/kicad-cli",
    # Windows (KiCad 7+)
    "C:/Program Files/KiCad/8.0/bin/kicad-cli.exe",
    "C:/Program Files/KiCad/9.0/bin/kicad-cli.exe",
    "C:/Program Files/KiCad/10.0/bin/kicad-cli.exe",
    "C:/Program Files/KiCad/7.0/bin/kicad-cli.exe",
]


# ======================================================================
# Result models
# ======================================================================


def _secure_temp_report_path(*, suffix: str) -> Path:
    """Create and close a unique temporary report path for kicad-cli output."""
    with tempfile.NamedTemporaryFile(prefix="zaptrace-kicad-", suffix=suffix, delete=False) as handle:
        return Path(handle.name)


def _portable_path_text(path: str | Path) -> str:
    """Return a platform-neutral path string for evidence payloads."""
    return str(path).replace("\\", "/")


def _sha256_if_readable(path: Path) -> str:
    """Return SHA-256 for a file path when readable, else an empty string."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return ""


@dataclass
class KiCadResult:
    """Base result for any KiCad oracle operation."""

    available: bool
    """Whether the KiCad CLI was found and executed."""

    success: bool = False
    """Whether the operation completed without errors."""

    message: str = ""
    """Human-readable summary."""

    duration_ms: float = 0.0
    """Wall-clock time for the operation."""

    version: str = ""
    """Detected kicad-cli version, when available."""

    cli_path: str = ""
    """Resolved kicad-cli executable path, when available."""

    command: list[str] = field(default_factory=list)
    """Executed command, if any."""

    exit_code: int | None = None
    """Process exit code, if a command ran."""

    report_path: str | None = None
    """Path to the structured report generated by kicad-cli, if any."""

    report_sha256: str = ""
    """SHA-256 hex digest of report_path, if readable."""

    @property
    def error(self) -> str:
        """Human-readable error when the operation failed, else empty."""
        return self.message if not self.success else ""


@dataclass
class KiCadErcItem:
    """A single ERC violation from the KiCad report."""

    rule: str = ""
    severity: str = "error"
    message: str = ""
    sheet: str = ""
    item: str = ""  # e.g. "J1:1 -> U1:10"
    comment: list[str] = field(default_factory=list)
    source: list[dict] | None = None


@dataclass
class KiCadErcResult(KiCadResult):
    """ERC check result with structured violations."""

    violations: list[KiCadErcItem] = field(default_factory=list)
    errors: int = 0
    warnings: int = 0

    @property
    def passed(self) -> bool:
        return self.success and self.errors == 0

    def to_oracle_evidence(
        self,
        *,
        check: str = "schematic_erc",
        approval_id: str = "",
        waiver_reason: str = "",
    ) -> Any:
        """Convert this ERC result into proof-pack KiCad oracle evidence."""
        from zaptrace.proof.manifest import KiCadOracleEvidence

        if not self.available:
            status = "skipped"
            skip_reason = self.message or "kicad-cli not available"
        elif self.passed:
            status = "passed"
            skip_reason = ""
        elif approval_id and waiver_reason:
            status = "waived"
            skip_reason = ""
        else:
            status = "failed"
            skip_reason = ""
        return KiCadOracleEvidence(
            check=check,
            status=status,
            version=self.version,
            cli_path=self.cli_path,
            command=self.command,
            exit_code=self.exit_code,
            report_path=self.report_path,
            report_sha256=self.report_sha256,
            errors=self.errors,
            warnings=self.warnings,
            message=self.message,
            skip_reason=skip_reason,
            approval_id=approval_id,
            waiver_reason=waiver_reason,
        )

    @property
    def violation_count(self) -> int:
        return len(self.violations)

    @property
    def error_count(self) -> int:
        return self.errors

    @property
    def warning_count(self) -> int:
        return self.warnings


@dataclass
class KiCadDrcItem:
    """A single DRC violation from the KiCad report."""

    rule: str = ""
    severity: str = "error"
    message: str = ""
    layer: str = ""
    position: tuple[float, float] | None = None
    code: int = 0
    comment: list[str] = field(default_factory=list)


@dataclass
class KiCadDrcResult(KiCadResult):
    """DRC check result with structured violations."""

    violations: list[KiCadDrcItem] = field(default_factory=list)
    errors: int = 0
    warnings: int = 0

    @property
    def passed(self) -> bool:
        return self.success and self.errors == 0

    def to_oracle_evidence(
        self,
        *,
        check: str = "pcb_drc",
        approval_id: str = "",
        waiver_reason: str = "",
    ) -> Any:
        """Convert this DRC result into proof-pack KiCad oracle evidence."""
        from zaptrace.proof.manifest import KiCadOracleEvidence

        if not self.available:
            status = "skipped"
            skip_reason = self.message or "kicad-cli not available"
        elif self.passed:
            status = "passed"
            skip_reason = ""
        elif approval_id and waiver_reason:
            status = "waived"
            skip_reason = ""
        else:
            status = "failed"
            skip_reason = ""
        return KiCadOracleEvidence(
            check=check,
            status=status,
            version=self.version,
            cli_path=self.cli_path,
            command=self.command,
            exit_code=self.exit_code,
            report_path=self.report_path,
            report_sha256=self.report_sha256,
            errors=self.errors,
            warnings=self.warnings,
            message=self.message,
            skip_reason=skip_reason,
            approval_id=approval_id,
            waiver_reason=waiver_reason,
        )

    @property
    def violation_count(self) -> int:
        return len(self.violations)

    @property
    def error_count(self) -> int:
        return self.errors

    @property
    def warning_count(self) -> int:
        return self.warnings


_OracleResult = KiCadErcResult | KiCadDrcResult


def _report_items(violation: dict[str, Any]) -> list[dict[str, Any]]:
    items = violation.get("items", [])
    return [item for item in items if isinstance(item, dict)] if isinstance(items, list) else []


def _item_descriptions(violation: dict[str, Any]) -> list[str]:
    return [str(item.get("description", "")) for item in _report_items(violation) if item.get("description")]


def _first_report_position(violation: dict[str, Any]) -> tuple[float, float] | None:
    direct = violation.get("position")
    if isinstance(direct, dict) and "x" in direct and "y" in direct:
        return (float(direct["x"]), float(direct["y"]))
    for item in _report_items(violation):
        pos = item.get("pos")
        if isinstance(pos, dict) and "x" in pos and "y" in pos:
            return (float(pos["x"]), float(pos["y"]))
    return None


def _erc_violation_rows(raw: dict[str, Any]) -> list[tuple[dict[str, Any], str]]:
    sheets = raw.get("sheets")
    if isinstance(sheets, list):
        rows: list[tuple[dict[str, Any], str]] = []
        for sheet in sheets:
            if not isinstance(sheet, dict):
                continue
            sheet_path = str(sheet.get("path", ""))
            violations = sheet.get("violations", [])
            if isinstance(violations, list):
                rows.extend((violation, sheet_path) for violation in violations if isinstance(violation, dict))
        return rows
    violations = raw.get("violations", [])
    if not isinstance(violations, list):
        return []
    return [(violation, str(violation.get("sheet", ""))) for violation in violations if isinstance(violation, dict)]


def _erc_item(violation: dict[str, Any], *, sheet_path: str) -> KiCadErcItem:
    descriptions = _item_descriptions(violation)
    source = _report_items(violation) or violation.get("source")
    return KiCadErcItem(
        rule=str(violation.get("rule") or violation.get("type") or ""),
        severity=str(violation.get("severity", "error")),
        message=str(violation.get("message") or violation.get("description") or ""),
        sheet=str(violation.get("sheet") or sheet_path),
        item=str(violation.get("item") or (descriptions[0] if descriptions else "")),
        comment=list(violation.get("comment", [])) if isinstance(violation.get("comment", []), list) else [],
        source=source if isinstance(source, list) else None,
    )


def _drc_violation_rows(raw: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for key in ("violations", "unconnected_items", "schematic_parity"):
        values = raw.get(key, [])
        if isinstance(values, list):
            rows.extend(value for value in values if isinstance(value, dict))
    return rows


def _drc_item(violation: dict[str, Any]) -> KiCadDrcItem:
    descriptions = _item_descriptions(violation)
    return KiCadDrcItem(
        rule=str(violation.get("rule") or violation.get("type") or ""),
        severity=str(violation.get("severity", "error")),
        message=str(violation.get("message") or violation.get("description") or ""),
        layer=str(violation.get("layer", "")),
        position=_first_report_position(violation),
        code=int(violation.get("code", 0)),
        comment=list(violation.get("comment", [])) if "comment" in violation else descriptions,
    )


def _count_result_severity(result: _OracleResult, severity: str) -> None:
    if severity == "error":
        result.errors += 1
    elif severity == "warning":
        result.warnings += 1


def _apply_check_metadata(
    result: _OracleResult,
    *,
    elapsed_ms: float,
    version: str,
    cli_path: str,
    command: list[str],
    exit_code: int,
    report_path: Path,
) -> _OracleResult:
    result.available = True
    result.duration_ms = elapsed_ms
    result.version = version
    result.cli_path = cli_path
    result.command = command.copy()
    result.exit_code = exit_code
    result.report_path = _portable_path_text(report_path)
    result.report_sha256 = _sha256_if_readable(report_path)
    return result


def _finalize_check_result(
    result: _OracleResult,
    *,
    process: subprocess.CompletedProcess[str],
    check_name: str,
    exit_code_violations: bool,
) -> _OracleResult:
    # KiCad returns 5 when --exit-code-violations sees any reported finding,
    # including warnings. Preserve the existing legacy code-3 compatibility,
    # but let a parsed JSON report remain authoritative for finding severity;
    # other non-zero codes are execution failures.
    if exit_code_violations and process.returncode not in {0, 3, 5}:
        result.success = False
        result.message = process.stderr.strip() or f"{check_name} failed (exit {process.returncode})"
    result.success = result.success or process.returncode == 0
    result.message = result.message or (f"{check_name} complete: {result.errors} errors, {result.warnings} warnings")
    return result


# ======================================================================
# Oracle class
# ======================================================================


class KiCadOracle:
    """Detect and interact with the KiCad CLI.

    Usage:
        oracle = KiCadOracle()
        if oracle.available:
            print(oracle.version)
            erc = oracle.run_erc("project.kicad_pro")
    """

    def __init__(self, cli_path: str | None = None) -> None:
        self._cli_path: str | None = cli_path
        self._version: str = ""
        self._detect()

    # ------------------------------------------------------------------
    # Public properties
    # ------------------------------------------------------------------

    @property
    def available(self) -> bool:
        return self._cli_path is not None

    @property
    def cli_path(self) -> str | None:
        return self._cli_path

    @property
    def version(self) -> str:
        if not self._cli_path:
            return ""
        if not self._version:
            self._version = self._capture_version()
        return self._version

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    def _detect(self) -> None:
        """Locate the kicad-cli binary."""
        if self._cli_path:
            self._cli_path = self._resolve(self._cli_path)
            return

        # Try PATH first
        resolved = shutil.which("kicad-cli")
        if resolved:
            self._cli_path = resolved
            return

        # Try known install paths
        for p in _COMMON_KICAD_PATHS:
            if self._resolve(p):
                self._cli_path = p
                return

        self._cli_path = None

    @staticmethod
    def _resolve(path: str) -> str | None:
        """Resolve *path* — return the absolute path if it exists."""
        if not path:
            return None
        # shutil.which already resolved — just check
        if os.path.isfile(path):
            return os.path.abspath(path)
        resolved = shutil.which(path)
        if resolved and os.path.isfile(resolved):
            return resolved
        return None

    def _capture_version(self) -> str:
        """Run ``kicad-cli --version`` and return the output."""
        if not self._cli_path:
            return ""
        try:
            result = subprocess.run(
                [self._cli_path, "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                return result.stdout.strip()
            return ""
        except (subprocess.TimeoutExpired, OSError):
            return ""

    # ------------------------------------------------------------------
    # ERC
    # ------------------------------------------------------------------

    def _run_json_check(
        self,
        *,
        base: _OracleResult,
        command: list[str],
        report_path: Path,
        output_path: str | Path | None,
        timeout: int,
        started_at: float,
        parser: Callable[[dict[str, Any]], _OracleResult],
        check_name: str,
        exit_code_violations: bool,
    ) -> _OracleResult:
        import time

        try:
            process = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
            elapsed_ms = (time.perf_counter() - started_at) * 1000
            base = _apply_check_metadata(
                base,
                elapsed_ms=elapsed_ms,
                version=self.version,
                cli_path=self._cli_path or "",
                command=command,
                exit_code=process.returncode,
                report_path=report_path,
            )
            if report_path.exists():
                parsed = parser(json.loads(report_path.read_text(encoding="utf-8")))
                base = _apply_check_metadata(
                    parsed,
                    elapsed_ms=elapsed_ms,
                    version=self.version,
                    cli_path=self._cli_path or "",
                    command=command,
                    exit_code=process.returncode,
                    report_path=report_path,
                )
            return _finalize_check_result(
                base,
                process=process,
                check_name=check_name,
                exit_code_violations=exit_code_violations,
            )
        except FileNotFoundError:
            base.message = f"KiCad CLI not found at {self._cli_path}"
        except subprocess.TimeoutExpired:
            base.message = f"{check_name} timed out after {timeout}s"
        except json.JSONDecodeError as error:
            base.message = f"{check_name} output parse error: {error}"
        except Exception as error:
            base.message = f"{check_name} unexpected error: {error}"
        finally:
            if not output_path and report_path.exists():
                with suppress(OSError):
                    report_path.unlink()
        return base

    def run_erc(
        self,
        project_file: str | Path,
        *,
        output_path: str | Path | None = None,
        timeout: int = 120,
        severity: str = "all",
        exit_code_violations: bool = True,
    ) -> KiCadErcResult:
        """Run Electrical Rules Check via ``kicad-cli sch erc``.

        Args:
            project_file: Path to a ``.kicad_pro`` project file.
            output_path: Optional path for the JSON report. If omitted a
                temporary file is used.
            timeout: Max seconds to wait for the CLI.
            severity: ``"all"``, ``"error"``, or ``"warning"``.
            exit_code_violations: If True, KiCad returns a non-zero code when
                findings exist; parsed report severity still determines pass/fail.

        Returns:
            ``KiCadErcResult`` with structured violations.
        """
        import time

        base = KiCadErcResult(
            available=self.available,
            version=self.version,
            cli_path=self._cli_path or "",
        )
        if not self._cli_path:
            base.message = "KiCad CLI not found"
            return base

        started_at = time.perf_counter()
        project = Path(project_file)
        if not project.exists():
            base.message = f"Project file not found: {project}"
            base.duration_ms = (time.perf_counter() - started_at) * 1000
            return base

        report_path = Path(output_path) if output_path else _secure_temp_report_path(suffix="-erc.json")
        command = [
            self._cli_path,
            "sch",
            "erc",
            str(project),
            "--format",
            "json",
            "--output",
            str(report_path),
            f"--severity-{severity}",
        ]
        if exit_code_violations:
            command.append("--exit-code-violations")
        base.command = command.copy()
        base.report_path = _portable_path_text(report_path)
        base.report_sha256 = _sha256_if_readable(report_path)
        return cast(
            KiCadErcResult,
            self._run_json_check(
                base=base,
                command=command,
                report_path=report_path,
                output_path=output_path,
                timeout=timeout,
                started_at=started_at,
                parser=self._parse_erc_json,
                check_name="ERC",
                exit_code_violations=exit_code_violations,
            ),
        )

    @staticmethod
    def _parse_erc_json(raw: dict[str, Any]) -> KiCadErcResult:
        """Parse legacy and KiCad 10 ERC JSON reports into a structured result."""
        result = KiCadErcResult(available=True, success=True)
        rows = _erc_violation_rows(raw)

        for violation, sheet_path in rows:
            item = _erc_item(violation, sheet_path=sheet_path)
            result.violations.append(item)
            _count_result_severity(result, item.severity)

        result.message = f"{result.errors} ERC errors, {result.warnings} warnings"
        result.success = result.errors == 0
        return result

    # ------------------------------------------------------------------
    # DRC
    # ------------------------------------------------------------------

    def run_drc(
        self,
        pcb_file: str | Path,
        *,
        output_path: str | Path | None = None,
        timeout: int = 120,
        severity: str = "all",
        exit_code_violations: bool = True,
        schematic_parity: bool = False,
    ) -> KiCadDrcResult:
        """Run Design Rules Check via ``kicad-cli pcb drc``.

        Args:
            pcb_file: Path to a ``.kicad_pcb`` board file.
            output_path: Optional path for the JSON report.
            timeout: Max seconds to wait for the CLI.
            severity: ``"all"``, ``"error"``, or ``"warning"``.
            exit_code_violations: If True, KiCad returns a non-zero code when
                findings exist; parsed report severity still determines pass/fail.
            schematic_parity: Also check schematic-PCB parity.

        Returns:
            ``KiCadDrcResult`` with structured violations.
        """
        import time

        base = KiCadDrcResult(
            available=self.available,
            version=self.version,
            cli_path=self._cli_path or "",
        )
        if not self._cli_path:
            base.message = "KiCad CLI not found"
            return base

        started_at = time.perf_counter()
        board = Path(pcb_file)
        if not board.exists():
            base.message = f"PCB file not found: {board}"
            base.duration_ms = (time.perf_counter() - started_at) * 1000
            return base

        report_path = Path(output_path) if output_path else _secure_temp_report_path(suffix="-drc.json")
        command = [
            self._cli_path,
            "pcb",
            "drc",
            str(board),
            "--format",
            "json",
            "--output",
            str(report_path),
            f"--severity-{severity}",
        ]
        if exit_code_violations:
            command.append("--exit-code-violations")
        if schematic_parity:
            command.append("--schematic-parity")
        base.command = command.copy()
        base.report_path = _portable_path_text(report_path)
        base.report_sha256 = _sha256_if_readable(report_path)
        return cast(
            KiCadDrcResult,
            self._run_json_check(
                base=base,
                command=command,
                report_path=report_path,
                output_path=output_path,
                timeout=timeout,
                started_at=started_at,
                parser=self._parse_drc_json,
                check_name="DRC",
                exit_code_violations=exit_code_violations,
            ),
        )

    @staticmethod
    def _parse_drc_json(raw: dict[str, Any]) -> KiCadDrcResult:
        """Parse legacy and KiCad 10 DRC JSON reports into a structured result."""
        result = KiCadDrcResult(available=True, success=True)

        for violation in _drc_violation_rows(raw):
            item = _drc_item(violation)
            result.violations.append(item)
            _count_result_severity(result, item.severity)

        result.message = f"{result.errors} DRC errors, {result.warnings} warnings"
        result.success = result.errors == 0
        return result

    def __repr__(self) -> str:
        if self.available:
            return f"<KiCadOracle {self._cli_path} v{self.version}>"
        return "<KiCadOracle unavailable>"


# ======================================================================
# Module-level convenience functions
# ======================================================================

_ORACLE_CACHE: KiCadOracle | None = None


def detect_kicad() -> KiCadOracle:
    """Detect the KiCad CLI on this system.

    Results are cached — subsequent calls return the same ``KiCadOracle``
    instance.
    """
    global _ORACLE_CACHE
    if _ORACLE_CACHE is None:
        _ORACLE_CACHE = KiCadOracle()
    return _ORACLE_CACHE


def get_kicad_version() -> str | None:
    """Return the detected KiCad CLI version, or ``None``."""
    oracle = detect_kicad()
    return oracle.version or None


def run_erc(project_file: str | Path, **kwargs: Any) -> KiCadErcResult:
    """Convenience: detect, then run ERC."""
    return detect_kicad().run_erc(project_file, **kwargs)


def run_schematic_erc(schematic_or_project_file: str | Path, **kwargs: Any) -> KiCadErcResult:
    """Convenience alias for the release-gated schematic ERC oracle."""
    return detect_kicad().run_erc(schematic_or_project_file, **kwargs)


def run_drc(pcb_file: str | Path, **kwargs: Any) -> KiCadDrcResult:
    """Convenience: detect, then run DRC."""
    return detect_kicad().run_drc(pcb_file, **kwargs)


def run_pcb_drc(pcb_file: str | Path, **kwargs: Any) -> KiCadDrcResult:
    """Convenience alias for the release-gated PCB DRC oracle."""
    return detect_kicad().run_drc(pcb_file, **kwargs)
