"""Guard documentation/status claims against stale code facts."""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import time
import urllib.request
from collections import Counter
from collections.abc import Callable
from pathlib import Path
from typing import Any

_STALE_TEST_TOTAL_REASON = "test totals should not be hard-coded in docs"
COMPONENT_TRUST_BASELINE_PATH = "config/component-trust-baseline.json"
PUBLIC_FACTS_PATH = "config/public-facts.json"

BANNED_REFERENCES = {
    "zaptrace/proof/generator.py": "proof generator module was consolidated into zaptrace/proof/pack.py",
    "8 ERC rules": "ERC rule count is generated from zaptrace.erc.runner._ALL_RULES",
    'ERC "8 rules"': "ERC rule count is generated from zaptrace.erc.runner._ALL_RULES",
    "629+ tests": _STALE_TEST_TOTAL_REASON,
    "629 passing": _STALE_TEST_TOTAL_REASON,
    "629 tests": _STALE_TEST_TOTAL_REASON,
    "543 tests passing": _STALE_TEST_TOTAL_REASON,
    "zaptrace/plugins/": "the current plugin package is zaptrace/plugin/",
    "| Fuzzing | Missing |": "bounded and scheduled fuzz workflows are implemented",
    "fuzzing workflow because no fuzz harness exists": "bounded and scheduled fuzz workflows are implemented",
    "heavy Docker vulnerability scan because": "exact-image Trivy scanning is implemented",
    "checksum manifest automation if required": "the release workflow generates and verifies SHA256SUMS",
    "Admin-enforced branch protection was not enabled": "main is protected by the committed active repository ruleset",
    "machine-verifiable periodic capture is still future work": "live ruleset evidence is generated by repository CI",
    "Branch protection continues to require the three stable Python check names": (
        "the active ruleset requires stable aggregate gate contexts"
    ),
    "https://github.com/oaslananka/zaptrace/issues/302": (
        "issue #302 was deleted and cannot be a public tracking reference"
    ),
    "GitHub Discussions is currently disabled": "the repository Discussions channel is enabled",
    "no analog simulation (yet)": "bounded ngspice-backed evidence gates are implemented",
    "At least one maintainer review required": "independent approval is not enforced in the solo-maintainer model",
    "~50 packages supported": f"component inventory is derived from {COMPONENT_TRUST_BASELINE_PATH}",
    "KiCad export is unidirectional": "KiCad schematic, PCB, and hierarchical project importers are implemented",
    "No release automation": "the release workflow builds, attests, checksums, and publishes GitHub release artifacts",
    "not yet on PyPI": "PyPI publication is active for verified releases (v0.3.3+); distribution name is zaptrace-eda",
}

ROOTS = (Path("README.md"), Path("CONTRIBUTING.md"), Path("docs"), Path("CHANGELOG.md"))
MCP_TOOLS_LABEL = "MCP tools"
GOVERNED_DOCS = [
    "docs/mcp/quickstart.md",
    "docs/installation/distribution-support.md",
    "docs/strategy/current-state-audit.md",
    "docs/GETTING_STARTED.md",
    "docs/releases/v0.3.0-evidence-hardening.md",
    "docs/repo-maturity-report.md",
]


def _list_len_assignment(path: str, name: str) -> int:
    """Return the element count of a module-level ``name = [...]`` list literal.

    Handles both plain assignments (``name = [...]``) and annotated
    assignments (``name: list[T] = [...]``).
    """
    tree = ast.parse(Path(path).read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            targets = [t for t in node.targets if isinstance(t, ast.Name) and t.id == name]
            value = node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            targets = [node.target]
            value = node.value
        else:
            continue
        if targets and isinstance(value, ast.List):
            return len(value.elts)
    raise RuntimeError(f"Could not find {name} in {path}")


def actual_erc_rule_count() -> int:
    return _list_len_assignment("zaptrace/erc/runner.py", "_ALL_RULES")


def actual_drc_rule_count() -> int:
    return _list_len_assignment("zaptrace/ee/drc/engine.py", "_ALL_CHECKS")


def actual_tool_count() -> int:
    """Return the declarative public design-tool count."""
    return _list_len_assignment("zaptrace/agent/tool_impls/registry.py", "_TOOL_ORDER")


def actual_mcp_admin_tool_names() -> list[str]:
    """Return module-level administrative tools registered directly on FastMCP."""
    tree = ast.parse(Path("zaptrace/mcp/server.py").read_text(encoding="utf-8"))
    names: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            target = decorator.func if isinstance(decorator, ast.Call) else decorator
            if (
                isinstance(target, ast.Attribute)
                and target.attr == "tool"
                and isinstance(target.value, ast.Name)
                and target.value.id == "server"
            ):
                names.append(node.name)
                break
    return sorted(names)


def actual_mcp_tool_count() -> int:
    """Return all MCP-exposed tools: design registry plus session administration."""
    return actual_tool_count() + len(actual_mcp_admin_tool_names())


def _iter_docs() -> list[Path]:
    paths: list[Path] = []
    for root in ROOTS:
        if root.is_file():
            paths.append(root)
        elif root.is_dir():
            paths.extend(path for path in root.rglob("*") if path.suffix.lower() in {".md", ".txt", ".json"})
    return sorted(paths)


def component_library_profile(path: Path = Path(COMPONENT_TRUST_BASELINE_PATH)) -> dict[str, Any]:
    """Return the committed component-library baseline used by CI."""
    data = json.loads(path.read_text(encoding="utf-8"))
    tiers = Counter(str(value) for value in data.get("component_tiers", {}).values())
    return {
        "source": str(path).replace("\\", "/"),
        "component_count": int(data["component_count"]),
        "schema_version": str(data.get("component_schema_version", "unknown")),
        "trust_tier_counts": dict(sorted(tiers.items())),
    }


def load_public_facts() -> dict[str, Any]:
    """Load the machine-readable public facts source."""
    path = Path(PUBLIC_FACTS_PATH)
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def source_revision() -> str:
    """Return the exact repository revision that produced the docs-status report."""
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    revision = completed.stdout.strip()
    return revision if re.fullmatch(r"[0-9a-fA-F]{40}", revision) else "unknown"


def internal_public_plan_paths(root: Path = Path("docs")) -> list[str]:
    """Return internal implementation-plan paths that must not be public docs."""
    internal_root = root / "superpowers"
    if not internal_root.exists():
        return []
    return sorted(str(path).replace("\\", "/") for path in internal_root.rglob("*") if path.is_file())


def navigation_gaps(root: Path = Path("docs"), config: Path = Path("mkdocs.yml")) -> list[str]:
    """Return Markdown pages not referenced by the MkDocs navigation."""
    text = config.read_text(encoding="utf-8")
    navigated = set(re.findall(r":\s*([^\s#]+\.md)\s*$", text, re.MULTILINE))
    pages = {str(path.relative_to(root)).replace("\\", "/") for path in root.rglob("*.md")}
    return sorted(pages - navigated)


def repository_capabilities() -> dict[str, bool]:
    """Derive selected public capability facts from committed source files."""
    fuzz = Path(".github/workflows/fuzz.yml")
    container = Path(".github/workflows/container-security.yml")
    release = Path(".github/workflows/release.yml")
    ruleset = Path("config/github-main-ruleset.json")
    ci = Path(".github/workflows/ci.yml")
    kicad_importer = Path("zaptrace/kicad/project_importer.py")
    release_text = release.read_text(encoding="utf-8") if release.is_file() else ""
    return {
        "fuzz_workflow": fuzz.is_file() and "bounded" in fuzz.read_text(encoding="utf-8").lower(),
        "container_scan": container.is_file()
        and "Generate Trivy JSON" in container.read_text(encoding="utf-8")
        and "ci_container_scan_policy.py" in container.read_text(encoding="utf-8"),
        "checksum_manifest": "Generate checksum manifest" in release_text,
        "main_ruleset_policy": ruleset.is_file()
        and ci.is_file()
        and "ci_repository_ruleset.py" in ci.read_text(encoding="utf-8"),
        "kicad_project_import": kicad_importer.is_file()
        and "def import_kicad_project(" in kicad_importer.read_text(encoding="utf-8"),
        "github_release": "Create GitHub release" in release_text and "softprops/action-gh-release" in release_text,
        "sbom_generation": "Generate SBOM" in release_text,
        "release_attestation": "actions/attest-build-provenance" in release_text,
    }


def _claim_checks(
    erc_count: int,
    drc_count: int,
    design_tool_count: int,
    mcp_tool_count: int,
) -> list[tuple[re.Pattern[str], int, str]]:
    return [
        (re.compile(r"(?<![\d.])(\d+)[ \t]+ERC[ \t]+rules\b", re.IGNORECASE), erc_count, "ERC rules"),
        (re.compile(r"\bERC[ \t]*\((\d+)[ \t]+rules?\)", re.IGNORECASE), erc_count, "ERC rules"),
        (re.compile(r"(?<![\d.])(\d+)[ \t]+DRC[ \t]+rules\b", re.IGNORECASE), drc_count, "DRC rules"),
        (re.compile(r"\bDRC[ \t]*\((\d+)[ \t]+rules?\)", re.IGNORECASE), drc_count, "DRC rules"),
        (
            re.compile(r"(?<![\d.])(\d+)[ \t]+agent[- ]facing[ \t]+tools\b", re.IGNORECASE),
            design_tool_count,
            "agent design tools",
        ),
        (re.compile(r"(?<![\d.])(\d+)[ \t]+design[ \t]+tools\b", re.IGNORECASE), design_tool_count, "design tools"),
        (
            re.compile(r"Tool Registry[^(\n]*\((\d+)[ \t]+tools", re.IGNORECASE),
            design_tool_count,
            "registry tools",
        ),
        (re.compile(r"MCP server[ \t]*\((\d+)[ \t]+tools\)", re.IGNORECASE), mcp_tool_count, MCP_TOOLS_LABEL),
        (re.compile(r"(?<![\d.])(\d+)[ \t]+tools[ \t]+total\b", re.IGNORECASE), mcp_tool_count, MCP_TOOLS_LABEL),
        (re.compile(r"(?<![\d.])(\d+)[ \t]+exposed[ \t]+tools\b", re.IGNORECASE), mcp_tool_count, MCP_TOOLS_LABEL),
    ]


def _validate_repository_facts(capabilities: dict[str, bool]) -> list[str]:
    errors = [
        f"repository capability evidence missing or incomplete: {name}"
        for name, available in capabilities.items()
        if not available
    ]
    errors.extend(f"mkdocs.yml: public page missing from navigation: docs/{gap}" for gap in navigation_gaps())
    errors.extend(
        f"public docs contain internal implementation material: {path}" for path in internal_public_plan_paths()
    )
    return errors


def _validate_current_state_document(path: Path = Path("docs/strategy/current-state-audit.md")) -> list[str]:
    """Validate machine-derived claims that are allowed in the current-state audit."""
    profile = component_library_profile()
    checks = [
        (
            re.compile(r"(?<![\d.])(\d+)[ \t]+component[ \t]+records\b", re.IGNORECASE),
            int(profile["component_count"]),
            "component records",
        )
    ]
    errors = _validate_document(path, checks)
    text = path.read_text(encoding="utf-8", errors="ignore")
    for required in (COMPONENT_TRUST_BASELINE_PATH, "scripts/ci_docs_status_sync.py"):
        if required not in text:
            errors.append(f"{path}: missing current-state evidence source {required}")
    return errors


def _validate_release_documentation() -> list[str]:
    errors: list[str] = []
    document = Path("docs/development/validation-environment.md").read_text(encoding="utf-8")
    required_arguments = (
        "--risky-package-reviewed",
        '--risky-package-approval-id "GENERATED-BOARD-BASELINE-REVIEW-2026-07-22"',
    )
    for argument in required_arguments:
        if argument not in document:
            errors.append(f"docs/development/validation-environment.md: missing CI release argument {argument}")
    readme = Path("README.md").read_text(encoding="utf-8")
    discussions_url = "https://github.com/oaslananka/zaptrace/discussions"
    if discussions_url not in readme:
        errors.append("README.md: missing the enabled GitHub Discussions support channel")
    if "GitHub Discussions is currently disabled" in readme:
        errors.append("README.md: claims GitHub Discussions is disabled even though the channel is enabled")
    return errors


def _validate_public_facts(
    public_facts: dict[str, Any],
    revision: str,
    deployment_evidence_path: Path | None = None,
) -> list[str]:
    """Validate that governed documentation matches the public-facts source."""
    errors: list[str] = []
    if not public_facts:
        errors.append("public-facts.json: missing or unreadable")
        return errors

    # Validate package info
    pkg = public_facts.get("package", {})
    dist = public_facts.get("distribution", {})
    mcp = public_facts.get("mcp", {})
    docs = public_facts.get("documentation", {})

    # Check that the deployment source SHA matches expected revision fail-closed
    deployment_sha = docs.get("deployment_source_sha")
    if not deployment_sha or deployment_sha == "unknown":
        errors.append(
            "documentation deployment_source_sha is missing or 'unknown'; "
            "must be bound to expected revision ('HEAD' or 40-character SHA) fail-closed"
        )
    elif deployment_sha == "HEAD":
        pass  # dynamically bound to repository revision being validated
    elif re.fullmatch(r"[0-9a-fA-F]{40}", deployment_sha):
        if deployment_sha != revision:
            deployed_short = deployment_sha[:8]
            current_short = revision[:8]
            errors.append(
                f"documentation deployment source SHA mismatch: deployed from {deployed_short} "
                f"but current revision is {current_short}"
            )
    else:
        errors.append(
            f"documentation deployment_source_sha invalid: {deployment_sha!r}; "
            "must be 'HEAD' or a 40-character commit SHA"
        )

    # Validate deployment provenance evidence if present or explicitly configured
    evidence_file = deployment_evidence_path
    if evidence_file is None and "deployment_evidence_path" in docs:
        candidate = Path(docs["deployment_evidence_path"])
        if candidate.is_file():
            evidence_file = candidate

    if evidence_file is not None:
        if not evidence_file.is_file():
            errors.append(f"deployment provenance evidence file not found: {evidence_file}")
        else:
            try:
                evidence_data = json.loads(evidence_file.read_text(encoding="utf-8"))
                evidence_sha = str(evidence_data.get("source_sha", ""))
                if not re.fullmatch(r"[0-9a-fA-F]{40}", evidence_sha):
                    errors.append(f"deployment provenance evidence contains invalid source_sha: {evidence_sha!r}")
                elif evidence_sha != revision:
                    errors.append(
                        f"deployment provenance evidence mismatch: evidence SHA {evidence_sha[:8]} "
                        f"does not match expected revision {revision[:8]}"
                    )
            except (json.JSONDecodeError, OSError) as exc:
                errors.append(f"failed to read deployment provenance evidence from {evidence_file}: {exc}")

    # Validate MCP tool counts in governed docs
    expected_mcp_total = mcp.get("total_exposed_tool_count", 96)
    expected_design_tools = mcp.get("design_tool_count", 93)
    _ = mcp.get("session_admin_tool_count", 3)  # validated via total count

    for doc_path_str in GOVERNED_DOCS:
        doc_path = Path(doc_path_str)
        if not doc_path.is_file():
            errors.append(f"governed doc missing: {doc_path_str}")
            continue
        text = doc_path.read_text(encoding="utf-8", errors="ignore")

        # Check MCP tool count claims
        mcp_total_pattern = re.compile(
            r"(?<![\d.])(\d+)[ \t]+(?:tools?\s+total|exposed\s+tools?|MCP[- ]?exposed)\b", re.IGNORECASE
        )
        for match in mcp_total_pattern.finditer(text):
            claimed = int(match.group(1))
            if claimed != expected_mcp_total:
                errors.append(f"{doc_path_str}: claims {claimed} MCP tools but public-facts has {expected_mcp_total}")

        design_tools_pattern = re.compile(r"(?<![\d.])(\d+)[ \t]+design\s+tools?\b", re.IGNORECASE)
        for match in design_tools_pattern.finditer(text):
            claimed = int(match.group(1))
            if claimed != expected_design_tools:
                errors.append(
                    f"{doc_path_str}: claims {claimed} design tools but public-facts has {expected_design_tools}"
                )

        # Check distribution claims
        if "not yet on PyPI" in text:
            errors.append(f"{doc_path_str}: contains stale 'not yet on PyPI' claim; PyPI publication is active")

        # Check latest published tag - validate against public-facts
        latest_tag = pkg.get("latest_published_tag", "v0.3.3")
        if "latest published" in text.lower() or "latest release" in text.lower():
            tag_pattern = re.compile(r"\bv?(\d+\.\d+\.\d+)\b")
            found_latest = False
            for match in tag_pattern.finditer(text):
                version = match.group(1)
                if f"v{version}" == latest_tag or version == latest_tag.lstrip("v"):
                    found_latest = True
                    break
            if not found_latest:
                errors.append(
                    f"{doc_path_str}: discusses 'latest published' or 'latest release' but does not mention "
                    f"the expected latest tag {latest_tag}"
                )

    # Cross-check distribution channels
    active_channels = [c["name"] for c in dist.get("channels", []) if c.get("status") == "active"]
    if "pypi" in active_channels:
        pypi_disabled_pattern = re.compile(r"PyPI.*not.*enabled", re.IGNORECASE)
        for doc_path_str in GOVERNED_DOCS:
            doc_path = Path(doc_path_str)
            if doc_path.is_file():
                text = doc_path.read_text(encoding="utf-8", errors="ignore")
                if "not yet on PyPI" in text or pypi_disabled_pattern.search(text):
                    errors.append(f"{doc_path_str}: claims PyPI not enabled but public-facts shows PyPI active")

    return errors


def _validate_document(path: Path, checks: list[tuple[re.Pattern[str], int, str]]) -> list[str]:
    errors: list[str] = []
    text = path.read_text(encoding="utf-8", errors="ignore")
    errors.extend(
        f"{path}: banned stale reference {banned!r}: {reason}"
        for banned, reason in BANNED_REFERENCES.items()
        if banned in text
    )
    for pattern, actual, label in checks:
        for match in pattern.finditer(text):
            claimed = int(match.group(1))
            if claimed != actual:
                errors.append(f"{path}: claims {claimed} {label} but code has {actual}")
    return errors


def validate_docs(deployment_evidence_path: Path | None = None) -> dict[str, Any]:
    erc_count = actual_erc_rule_count()
    drc_count = actual_drc_rule_count()
    tool_count = actual_tool_count()
    mcp_admin_tools = actual_mcp_admin_tool_names()
    mcp_tool_count = tool_count + len(mcp_admin_tools)
    capabilities = repository_capabilities()
    component_library = component_library_profile()
    revision = source_revision()
    public_facts = load_public_facts()
    checks = _claim_checks(erc_count, drc_count, tool_count, mcp_tool_count)

    errors = _validate_repository_facts(capabilities)
    if revision == "unknown":
        errors.append("repository revision identity is unavailable")
    errors.extend(_validate_release_documentation())
    errors.extend(_validate_current_state_document())
    errors.extend(_validate_public_facts(public_facts, revision, deployment_evidence_path=deployment_evidence_path))
    for path in _iter_docs():
        if path != Path("docs/strategy/current-state-audit.md"):
            errors.extend(_validate_document(path, checks))

    docs_info = public_facts.get("documentation", {})
    return {
        "passed": not errors,
        "erc_rule_count": erc_count,
        "drc_rule_count": drc_count,
        "tool_count": tool_count,
        "mcp_admin_tools": mcp_admin_tools,
        "mcp_tool_count": mcp_tool_count,
        "capabilities": capabilities,
        "component_library": component_library,
        "source_revision": revision,
        "public_facts": public_facts,
        "deployment_provenance": {
            "expected_sha": revision,
            "deployment_source_sha": docs_info.get("deployment_source_sha"),
            "audit_baseline_deployed_sha": docs_info.get("audit_baseline_deployed_sha"),
            "provenance_url": docs_info.get("deployment_provenance_url"),
            "freshness_check_enabled": docs_info.get("freshness_check_enabled", False),
        },
        "fact_sources": {
            "component_library": COMPONENT_TRUST_BASELINE_PATH,
            "public_facts": PUBLIC_FACTS_PATH,
            "docs_status": "scripts/ci_docs_status_sync.py",
            "kicad_project_import": "zaptrace/kicad/project_importer.py",
            "release": ".github/workflows/release.yml",
            "ruleset": "config/github-main-ruleset.json",
        },
        "navigation_gap_count": len(navigation_gaps()),
        "errors": errors,
    }


def _default_provenance_fetcher(target_url: str) -> str:
    req = urllib.request.Request(
        target_url,
        headers={"User-Agent": "zaptrace-freshness-verifier/1.0", "Cache-Control": "no-cache"},
    )
    with urllib.request.urlopen(req, timeout=10.0) as resp:
        return resp.read().decode("utf-8")


def verify_deployment_freshness(
    expected_sha: str,
    url: str = "https://oaslananka.github.io/zaptrace/deployment-provenance.json",
    max_attempts: int = 15,
    initial_backoff: float = 5.0,
    max_backoff: float = 30.0,
    backoff_multiplier: float = 1.5,
    timeout_seconds: float = 180.0,
    fetcher: Callable[[str], str] | None = None,
    sleeper: Callable[[float], None] | None = None,
) -> dict[str, Any]:
    """Verify that deployed GitHub Pages provenance matches expected_sha with bounded robust polling."""
    fetch = fetcher or _default_provenance_fetcher
    sleep_fn = sleeper or time.sleep
    start_time = time.time()
    backoff = initial_backoff
    last_error = "no attempts made"
    history: list[dict[str, Any]] = []

    for attempt in range(1, max_attempts + 1):
        elapsed = time.time() - start_time
        if elapsed > timeout_seconds:
            last_error = (
                f"deployment freshness verification timed out after {elapsed:.1f}s (expected {expected_sha[:8]})"
            )
            break

        try:
            raw = fetch(url)
            data = json.loads(raw)
            deployed_sha = data.get("source_sha", "")
            deployed_ts = data.get("deployment_timestamp", "unknown")
            history.append(
                {
                    "attempt": attempt,
                    "deployed_sha": deployed_sha,
                    "timestamp": deployed_ts,
                    "elapsed_seconds": round(elapsed, 2),
                }
            )
            if deployed_sha == expected_sha:
                return {
                    "passed": True,
                    "expected_sha": expected_sha,
                    "deployed_sha": deployed_sha,
                    "deployment_timestamp": deployed_ts,
                    "attempts": attempt,
                    "elapsed_seconds": round(time.time() - start_time, 2),
                    "provenance": data,
                    "history": history,
                }
            deployed_repr = deployed_sha[:8] if deployed_sha else "empty"
            last_error = f"deployed source SHA ({deployed_repr}) does not match expected revision ({expected_sha[:8]})"
        except Exception as exc:
            last_error = f"fetch failed: {exc}"
            history.append(
                {
                    "attempt": attempt,
                    "error": str(exc),
                    "elapsed_seconds": round(elapsed, 2),
                }
            )

        if attempt < max_attempts:
            sleep_fn(backoff)
            backoff = min(max_backoff, backoff * backoff_multiplier)

    return {
        "passed": False,
        "expected_sha": expected_sha,
        "error": last_error,
        "attempts": min(attempt, max_attempts),
        "elapsed_seconds": round(time.time() - start_time, 2),
        "history": history,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate docs/status sync guard and deployment freshness")
    parser.add_argument("--output", type=Path, help="Write JSON verification report")
    parser.add_argument("--deployment-evidence", type=Path, help="Path to local deployment provenance evidence file")
    parser.add_argument("--verify-freshness", action="store_true", help="Perform post-deploy freshness verification")
    parser.add_argument("--expected-sha", type=str, help="Expected source SHA for freshness verification")
    parser.add_argument("--provenance-url", type=str, help="Deployment provenance URL for freshness verification")
    parser.add_argument("--max-attempts", type=int, default=15, help="Max polling attempts")
    parser.add_argument("--timeout", type=float, default=180.0, help="Max total timeout in seconds")
    args = parser.parse_args(argv)

    if args.verify_freshness:
        expected = args.expected_sha or source_revision()
        if not expected or expected == "unknown":
            print("error: expected SHA must be provided or resolvable from git", file=sys.stderr)
            return 1
        url = args.provenance_url
        if not url:
            facts = load_public_facts()
            url = facts.get("documentation", {}).get(
                "deployment_provenance_url",
                "https://oaslananka.github.io/zaptrace/deployment-provenance.json",
            )
        result = verify_deployment_freshness(
            expected_sha=expected,
            url=url,
            max_attempts=args.max_attempts,
            timeout_seconds=args.timeout,
        )
        if args.output:
            args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if not result["passed"]:
            print(f"FRESHNESS CHECK FAILED: {result.get('error')}", file=sys.stderr)
            return 1
        print(
            f"freshness-check passed: deployed documentation matches expected revision {expected[:8]} "
            f"after {result['attempts']} attempts"
        )
        return 0

    result = validate_docs(deployment_evidence_path=args.deployment_evidence)
    if args.output:
        args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not result["passed"]:
        for error in result["errors"]:
            print(error)
        return 1
    print(
        "docs-status-sync ok: "
        f"ERC rules={result['erc_rule_count']}, "
        f"DRC rules={result['drc_rule_count']}, "
        f"design tools={result['tool_count']}, "
        f"MCP-exposed tools={result['mcp_tool_count']}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
